# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle
# Comment

name: Java CI with Gradle
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    name: Setting Env Variables
    runs-on: [self-hosted, linux, x64, stage]

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
    - name: display string
      env:
        SIEBEL_HOME: /opt/home
      run: |
        echo "The string is: ${{ steps.my_string.outputs.content }}"
        echo "We are here"
        echo $JAVA_HOME
        hostname
        
        echo $SIEBEL_HOME
        df -kh

